#!/bin/bash
cd /tmp
mkdir ansiblepackage
cd ansiblepackage
echo "enabling the epel and downloading the rpm pack of ansible"
Yum install wget -y
wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
rpm -ivh epel-release-latest-7.noarch.rpm          
cd /root
mkdir ansible
cd ansible
rm -r *.rpm
ll
echo "installing the ansible"
yum install ansible -y
echo "installed ansible"
ansible --version
